target 'iosApp' do
  use_frameworks!
  platform :ios, '15.0'
  pod 'SharedModule', :path => '../SharedModule'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
         end
    end
  end
end